
name: Apigee Connector / Integration / Proxy CI 

on: push
  
env:
  # Connection
  CONNECTOR_PROJECT_ID: "bap-emea-apigee-5"
  CONNECTOR_NAME: "cl-bqdemo1"
  CONNECTOR_LOCATION: "europe-west1"
  SERVICE_ACCOUNT: "1020259423319-compute@developer.gserviceaccount.com"

  # Big Query DataSet
  BQ_PROJECT_ID: "bap-emea-apigee-5"
  BQ_DATASET_ID: "ApigeeDemos"
  
  # Integration
  INTEGRATION_NAME: "cl-bqdemo1"
  INTEGRATION_LOCATION: "us"

  #  Apigee: 
  APIGEE_ORG: bap-emea-apigee-5
  APIGEE_CONFIG_ENV: <YOUR-CONF-ENV>
  TEST_HOST: <YOUR-HOSTNAME>


jobs:
  Apigee-Deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Apigee Acidt: install from GitHub g-lalevee/apigee-acidt
      - name: 'Install Apigee Acidt'
        run: |
          git clone https://github.com/g-lalevee/apigee-acidt.git


      # google-github-actions: Authenticate against Google Cloud with Service Account (Secret) 
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'


      # google-github-actions: Install and configure gcloud (alpha for Apigee commands)
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'


      # Retrieve list of connections
      - name: 'List Apigee Connections'
        run: |
          export TOKEN=$(gcloud auth print-access-token)
          ./apigee-acidt/bin/acidt connection list -o $APIGEE_ORG -t $TOKEN -r $CONNECTOR_LOCATION  --debug

      # Create new Connection
      - name: 'Create Apigee Connection'
        run: |
          sed -i "s/CONNECTOR_PROJECT_ID/$CONNECTOR_PROJECT_ID/g" ./connection/connection-bq-template.json 
          sed -i "s/BQ_PROJECT_ID/$BQ_PROJECT_ID/g" ./connection/connection-bq-template.json 
          sed -i "s/BQ_DATASET_ID/$BQ_DATASET_ID/g" ./connection/connection-bq-template.json 
          sed -i "s/SERVICE_ACCOUNT/$SERVICE_ACCOUNT/g" ./connection/connection-bq-template.json 

          export TOKEN=$(gcloud auth print-access-token)

          ./apigee-acidt/bin/acidt connection create -o $CONNECTOR_PROJECT_ID -t $TOKEN -r $CONNECTOR_LOCATION --name $CONNECTOR_NAME --file ./connection/connection-bq-template.json  --debug

      # Create new Integration
      - name: 'Create Apigee Integration'
        run: |
          export TOKEN=$(gcloud auth print-access-token)

          # retrieve Connector serviceName
          ./apigee-acidt/bin/acidt connection download -o $CONNECTOR_PROJECT_ID -t $TOKEN -r $CONNECTOR_LOCATION --name $CONNECTOR_NAME --directory . --debug
          CONNECTOR_SERVICE_DIRECTORY=$(cat $CONNECTOR_NAME.json | grep "serviceDirectory" | cut -d ':' -f2 | sed 's@"@@g' | xargs)

          # update Integration configuration file
          sed -i "s/CONNECTOR_PROJECT_ID/$CONNECTOR_PROJECT_ID/g" ./integration/integration-bq-template.json
          sed -i "s/CONNECTOR_NAME/$CONNECTOR_NAME/g" ./integration/integration-bq-template.json
          sed -i "s/CONNECTOR_LOCATION/$CONNECTOR_LOCATION/g" ./integration/integration-bq-template.json
          sed -i "s/CONNECTOR_SERVICE_DIRECTORY/$CONNECTOR_SERVICE_DIRECTORY/g" ./integration/integration-bq-template.json

          ./apigee-acidt/bin/acidt integration create  -o $CONNECTOR_PROJECT_ID -t $TOKEN -r $INTEGRATION_LOCATION --name $INTEGRATION_NAME --file ./integration/integration-bq-template.json --debug
          ./apigee-acidt/bin/acidt integration publish  -o $CONNECTOR_PROJECT_ID -t $TOKEN -r $INTEGRATION_LOCATION --name $INTEGRATION_NAME --debug