
name: Apigee Connectotr / Integration / Proxy CI 

on: push
  
env:
  # Connection
  CONNECTOR-PROJECT-ID: "bap-emea-apigee-5"
  CONNECTOR-NAME: "cl-bqdemo-1"
  CONNECTOR-LOCATION: "europe-west1"
  SERVICE-ACCOUNT: "1020259423319-compute@developer.gserviceaccount.com"

  # Big Query DataSet
  BQ-PROJECT-ID: "bap-emea-apigee-5"
  BQ-DATASET-ID: "ApigeeDemos"
  
  # Integration
  INTEGRATION-NAME: "cl-bqdemo-1"
  INTEGRATION-LOCATION: "us"

  #  Apigee: 
  APIGEE_ORG: bap-emea-apigee-5
  APIGEE_CONFIG_ENV: <YOUR-CONF-ENV>
  TEST_HOST: <YOUR-HOSTNAME>


jobs:
  Apigee-Deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Apigee Acidt: install from GitHub g-lalevee/apigee-acidt
      - name: 'Install Apigee Acidt'
        run: |
          git clone https://github.com/g-lalevee/apigee-acidt.git


      # google-github-actions: Authenticate against Google Cloud with Service Account (Secret) 
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'


      # google-github-actions: Install and configure gcloud (alpha for Apigee commands)
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'


      # Retrieve list of connections
      - name: 'List Apigee Connections'
        run: |
          export TOKEN=$(gcloud auth print-access-token)
          ./apigee-acidt/bin/acidt connection list -o $APIGEE_ORG -t $TOKEN -r $CONNECTOR-LOCATION  --debug

      # Create new Connection
      - name: 'Create Apigee Connection'
        run: |
          sed -i "s/BQ-PROJECT-ID/$BQ-PROJECT-ID/g" ./connection/connection-bq-template.json 
          sed -i "s/BQ-DATASET-ID/$BQ-DATASET-ID/g" ./connection/connection-bq-template.json 
          sed -i "s/SERVICE-ACCOUNT/$SERVICE-ACCOUNT/g" ./connection/connection-bq-template.json 

          export TOKEN=$(gcloud auth print-access-token)

          ./apigee-acidt/bin/acidt connection create -o $CONNECTOR-PROJECT-ID -t $TOKEN -r $CONNECTOR-LOCATION --name $CONNECTOR-NAME --file ./connection/connection-bq-template.json 

      # Create new Integration
      - name: 'Create Apigee Integration'
        run: |
          sed -i "s/CONNECTOR-PROJECT-ID/$CONNECTOR-PROJECT-ID/g" ./integration/integration-bq-template.json
          sed -i "s/CONNECTOR-NAME/$CONNECTOR-NAME/g" ./integration/integration-bq-template.json
          sed -i "s/CONNECTOR-LOCATION/$CONNECTOR-LOCATION/g" ./integration/integration-bq-template.json

          export TOKEN=$(gcloud auth print-access-token)

          ./apigee-acidt/bin/acidt integration create  -o $CONNECTOR-PROJECT-ID -t $TOKEN -r $INTEGRATION-LOCATION --name $INTEGRATION-NAME --file ./integration/integration-bq-template.json
          ./apigee-acidt/bin/acidt integration publish  -o $CONNECTOR-PROJECT-ID -t $TOKEN -r $INTEGRATION-LOCATION --name $INTEGRATION-NAME